# Homebrew cask for Loupe -- generated by packaging/update-cask.js in
# github.com/akshatgg/loupe; edit that, not this file.
#
# Homebrew ADDS com.apple.quarantine to casks by default. The postflight
# clears it, which is the same permission System Settings -> Privacy &
# Security -> Open Anyway grants by hand: the app is ad-hoc signed, not
# notarized (that needs a paid Apple Developer ID).

cask "loupe" do
  version "0.1.0"

  on_arm do
    sha256 "a3aa662793a187b6e617ea6d9b0f3a1b25c073ce3a8fe986bb672b54b15c8f51"
    url "https://github.com/akshatgg/loupe/releases/download/v#{version}/Loupe-arm64.dmg"
  end
  on_intel do
    sha256 "1556d461641444ae1f33c4a0de2bbd48a6a949c3399bcf086c729fbf24884390"
    url "https://github.com/akshatgg/loupe/releases/download/v#{version}/Loupe-x64.dmg"
  end

  name "Loupe"
  desc "Screen recorder that zooms in while you record"
  homepage "https://loupeapp.vercel.app"

  depends_on macos: ">= :sonoma"

  app "Loupe.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Loupe.app"],
                   must_succeed: false
  end

  uninstall quit: "tech.markai.loupe"

  # Recordings in ~/Movies/Loupe are the user's own files and are left alone.
  zap trash: [
    "~/Library/Application Support/Loupe",
    "~/Library/Preferences/tech.markai.loupe.plist",
    "~/Library/Saved Application State/tech.markai.loupe.savedState",
  ]
end
