# Homebrew cask for Loupe -- generated by packaging/update-cask.js in
# github.com/akshatgg/loupe; edit that, not this file.
#
# Loupe 2.1.1 exactly: brew install --cask akshatgg/tap/loupe@2.1.1
# For the newest release, install akshatgg/tap/loupe instead.
#
# Homebrew ADDS com.apple.quarantine to casks by default. The postflight
# steps clear it, which is the same permission System Settings -> Privacy &
# Security -> Open Anyway grants by hand: the app is ad-hoc signed, not
# notarized (that needs a paid Apple Developer ID).

cask "loupe@2.1.1" do
  version "2.1.1"

  on_arm do
    sha256 "48204e28f230cc17097a615d240f65416996904491c6c4082f065c2adb552d0c"

    url "https://github.com/akshatgg/loupe/releases/download/v#{version}/Loupe-arm64.dmg"
  end
  on_intel do
    sha256 "a9f0c83b49e950a871ace24aa376a9f30e6c91b08ca2fef82b7311320bff2a5d"

    url "https://github.com/akshatgg/loupe/releases/download/v#{version}/Loupe-x64.dmg"
  end

  name "Loupe"
  desc "Screen recorder that zooms in while you record"
  homepage "https://loupeapp.vercel.app/"

  conflicts_with cask: "loupe"
  depends_on macos: :sonoma

  app "Loupe.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "{{appdir}}/Loupe.app"],
        must_succeed: false
  end

  uninstall quit: "tech.markai.loupe"

  # Recordings in ~/Movies/Loupe are the user's own files and are left alone.
  zap trash: [
    "~/Library/Application Support/Loupe",
    "~/Library/Preferences/tech.markai.loupe.plist",
    "~/Library/Saved Application State/tech.markai.loupe.savedState",
  ]

  caveats <<~EOS
    Loupe offers to update itself when a newer version is out. To stay on
    #{version}, choose Later, or turn off Settings > Updates > Check for
    updates automatically.
  EOS
end
