# Homebrew cask for Loupe -- generated by packaging/update-cask.js in
# github.com/akshatgg/loupe; edit that, not this file.
#
# Loupe 0.1.0 exactly: brew install --cask akshatgg/tap/loupe@0.1.0
# For the newest release, install akshatgg/tap/loupe instead.
#
# Homebrew ADDS com.apple.quarantine to casks by default. The postflight
# steps clear it, which is the same permission System Settings -> Privacy &
# Security -> Open Anyway grants by hand: the app is ad-hoc signed, not
# notarized (that needs a paid Apple Developer ID).

cask "loupe@0.1.0" do
  version "0.1.0"

  on_arm do
    sha256 "7002657ee68f76e6b57915def7aa53a251d71ce39ed355c34ee9a80b867235e8"

    url "https://github.com/akshatgg/loupe/releases/download/v#{version}/Loupe-arm64.dmg"
  end
  on_intel do
    sha256 "abfe5520cfc20cc2afa916737673e4dd79cf10d60bb4e1360b71464f584f0364"

    url "https://github.com/akshatgg/loupe/releases/download/v#{version}/Loupe-x64.dmg"
  end

  name "Loupe"
  desc "Screen recorder that zooms in while you record"
  homepage "https://loupeapp.vercel.app/"

  conflicts_with cask: "loupe"
  depends_on macos: :sonoma

  app "Loupe.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "{{appdir}}/Loupe.app"],
        must_succeed: false
  end

  uninstall quit: "tech.markai.loupe"

  # Recordings in ~/Movies/Loupe are the user's own files and are left alone.
  zap trash: [
    "~/Library/Application Support/Loupe",
    "~/Library/Preferences/tech.markai.loupe.plist",
    "~/Library/Saved Application State/tech.markai.loupe.savedState",
  ]

  caveats <<~EOS
    Loupe offers to update itself when a newer version is out. To stay on
    #{version}, choose Later, or turn off Settings > Updates > Check for
    updates automatically.
  EOS
end
