# Homebrew cask for Loupe -- generated by packaging/update-cask.js in
# github.com/akshatgg/loupe; edit that, not this file.
#
# Loupe 2.0.0 exactly: brew install --cask akshatgg/tap/loupe@2.0.0
# For the newest release, install akshatgg/tap/loupe instead.
#
# Homebrew ADDS com.apple.quarantine to casks by default. The postflight
# steps clear it, which is the same permission System Settings -> Privacy &
# Security -> Open Anyway grants by hand: the app is ad-hoc signed, not
# notarized (that needs a paid Apple Developer ID).

cask "loupe@2.0.0" do
  version "2.0.0"

  on_arm do
    sha256 "7863f4f4ca0b5e6c3ee1486ae6b3a44df73976508f8274e31a6bfae6986fa952"

    url "https://github.com/akshatgg/loupe/releases/download/v#{version}/Loupe-arm64.dmg"
  end
  on_intel do
    sha256 "af8624415691142d01efad7af579c4100069bf9fae852365c3971c96c1fc76f9"

    url "https://github.com/akshatgg/loupe/releases/download/v#{version}/Loupe-x64.dmg"
  end

  name "Loupe"
  desc "Screen recorder that zooms in while you record"
  homepage "https://loupeapp.vercel.app/"

  conflicts_with cask: "loupe"
  depends_on macos: :sonoma

  app "Loupe.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "{{appdir}}/Loupe.app"],
        must_succeed: false
  end

  uninstall quit: "tech.markai.loupe"

  # Recordings in ~/Movies/Loupe are the user's own files and are left alone.
  zap trash: [
    "~/Library/Application Support/Loupe",
    "~/Library/Preferences/tech.markai.loupe.plist",
    "~/Library/Saved Application State/tech.markai.loupe.savedState",
  ]

  caveats <<~EOS
    Loupe offers to update itself when a newer version is out. To stay on
    #{version}, choose Later, or turn off Settings > Updates > Check for
    updates automatically.
  EOS
end
